################################################
#
#
#
#
#
################################################

FROM		alpine:latest
MAINTAINER	Ehud Kaldor <ehud@unfairfunction.org>

ENV		S6_LOGGING 1
ENV		S6_VERSION 1.21.2.2
ENV		CONFD_VERSION 0.14.0
ENV             ARCH armhf

RUN		apk add --update gnupg curl

ADD             https://github.com/just-containers/s6-overlay/releases/download/v$S6_VERSION/s6-overlay-$ARCH.tar.gz /tmp/
ADD             https://github.com/just-containers/s6-overlay/releases/download/v$S6_VERSION/s6-overlay-$ARCH.tar.gz.sig /tmp/
ADD 		https://github.com/kelseyhightower/confd/releases/download/v$CONFD_VERSION/confd-$CONFD_VERSION-linux-$ARCH /usr/local/bin/confd

RUN             curl https://keybase.io/justcontainers/key.asc | gpg --import && \
		gpg --verify /tmp/s6-overlay-$ARCH.tar.gz.sig /tmp/s6-overlay-$ARCH.tar.gz && \
		gunzip -c /tmp/s6-overlay-$ARCH.tar.gz | tar -xf - -C / && \
		chmod +x /usr/local/bin/confd

#		tar xzf /tmp/s6-overlay-$ARCH.tar.gz -C / --exclude="./bin" --exclude="./sbin" && \
#		tar xzf /tmp/s6-overlay-$ARCH.tar.gz -C /usr ./bin ./sbin


#RUN		echo "@testing http://nl.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories && \
# 		apk add --update libressl@testing && \
#RUN 		apk add --update dnsmasq jq curl && \
RUN		apk del curl gnupg && \
		rm -rf /tmp/* && \
		rm -rf /var/cache/apk/*

COPY		rootfs /

ENTRYPOINT	["/init"]
